version: '3.5'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY}/etcd:/etcd-data
    networks:
      - milvus-network

  minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY}/minio:/data
    networks:
      - milvus-network

  milvus:
    image: milvusdb/milvus:latest
    command: [ "milvus", "run", "standalone" ]
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - DATA_PATH=/milvus/data
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY}/milvus:/milvus-data
    depends_on:
      - etcd
      - minio
    networks:
      - milvus-network

networks:
  milvus-network:
    driver: bridge
